import { Event } from "./schemas";

export const EVENTS: Event[] = [
  {
    urlRewrite: "ceo-x-product-chill-and-chat",
    createdAt: "2025-08-19T04:27:59.317Z",
    updatedAt: "2025-08-27T02:44:57.588Z",
    publishedAt: "2025-08-19T07:52:07.721Z",
    title: "CEO x Product: Chill & Chat",
    description:
      "🌟Thảnh thơi trò chuyện, khai mở góc nhìn. Không gian trò chuyện đặc biệt giữa CEO và Product members.",
    notionId: null,
    content:
      '<h2><strong>Giới thiệu</strong></h2><p>Trong guồng quay công việc hằng ngày, không phải lúc nào chúng ta cũng có cơ hội <strong>ngồi lại cùng CEO để trao đổi trực tiếp</strong> về những vấn đề gắn liền với sản phẩm và định hướng phát triển. Chính vì vậy, chương trình <strong>CEO x Product: Chill &amp; Chat</strong> mở ra một không gian gần gũi nhưng đầy giá trị, nơi tiếng nói của Product members được lắng nghe và lan tỏa.</p><p>Không chỉ dừng lại ở lắng nghe, <strong>CEO sẽ phản hồi, chia sẻ góc nhìn và định hướng từ “ghế lái”</strong>, giúp các Product members hiểu rõ hơn về bức tranh toàn cảnh cũng như tầm nhìn tương lai của công ty.</p><p>✨ <strong>Vì sao bạn nên tham dự?</strong></p><ul><li>Đây là cơ hội hiếm có để được kết nối trực tiếp, gần gũi với CEO trong không khí thân mật.</li><li>Bạn sẽ nhận về không chỉ kiến thức, mà còn cả cảm hứng để tiếp tục đồng hành và xây dựng các sản phẩm đột phá.</li><li>Và quan trọng hơn cả: bạn chính là một phần trong hành trình định hình tương lai của MoMo.</li></ul><h2><strong>Thông tin chương trình</strong></h2><p><img src="https://product.momo.vn:1338/uploads/CEO_Product_17cf38cc0e.jpg" alt="CEO - Product.jpg"></p><h2><strong>Đăng ký tham dự</strong></h2><p>👉 Đừng bỏ lỡ dịp đặc biệt này để vừa “chill” vừa “chat” cùng CEO và đồng nghiệp Phát triển sản phẩm nhé.</p><div class="raw-html-embed"><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeoQkrX2SUf06cUJsxuyTurMFtL9uKAERlxWUSkTrWWxeFxyw/viewform?embedded=true" width="640" height="1708" frameborder="0" marginheight="0" marginwidth="0">Đang tải…</iframe></div>',
    urlImage: null,
    totalViews: null,
    totalPost: null,
    totalLikes: null,
    publishDate: null,
    location: null,
    isFeatured: true,
    startDateTime: "2025-09-04T09:30:00.000Z",
    meta: null,
    categoryName: ["Seminar"],
    coverImageUrl:
      "https://product.momo.vn:1338/uploads/Seminar_11_35a5f08df9.jpg",
    authors: [],
    id: 103,
  },
  {
    urlRewrite: "product-market-fit-frameworks-and-fintech-applications",
    createdAt: "2025-08-19T04:36:16.269Z",
    updatedAt: "2025-08-27T02:45:06.217Z",
    publishedAt: "2025-08-19T07:40:23.975Z",
    title: "Product-Market Fit: Frameworks & Fintech Applications",
    description: "Kết nối giá trị sản phẩm với nhu cầu thực tiễn.",
    notionId: null,
    content:
      "<p>📢 <strong>Sự kiện sắp diễn ra: Product-Market Fit – Frameworks &amp; Fintech Applications</strong>&nbsp;</p><p>Một buổi chia sẻ đặc biệt về hành trình tìm kiếm <strong>“điểm gặp gỡ” giữa sản phẩm và thị trường</strong>. Bạn sẽ khám phá framework thực tiễn, cùng những ứng dụng cụ thể trong lĩnh vực Fintech để biến ý tưởng thành sản phẩm có chỗ đứng vững chắc.</p><p>👉 Chi tiết sự kiện sẽ được update. Bạn hãy theo dõi để không bỏ lỡ những thông tin thú vị từ chương trình nhé.</p>",
    urlImage: null,
    totalViews: null,
    totalPost: null,
    totalLikes: null,
    publishDate: null,
    location: null,
    isFeatured: true,
    startDateTime: null,
    meta: null,
    categoryName: ["Seminar"],
    coverImageUrl:
      "https://product.momo.vn:1338/uploads/Seminar_7_8e8f5c0c02.jpg",
    authors: [],
    id: 104,
  },
  {
    urlRewrite:
      "data-and-decision-making-leading-products-in-an-imperfect-landscape",
    createdAt: "2025-08-19T03:14:19.367Z",
    updatedAt: "2025-08-27T02:45:29.080Z",
    publishedAt: "2025-08-19T07:35:54.272Z",
    title: "Data & Decision-Making Leading Products in an Imperfect Landscape",
    description: "Quyết định sáng suốt trong thế giới dữ liệu bất toàn.",
    notionId: null,
    content:
      '<h2><strong>Giới thiệu</strong></h2><p>Trong môi trường kinh doanh, câu nói “ra quyết định dựa trên dữ liệu” đã trở thành nguyên tắc quen thuộc. Nhưng đã bao nhiêu lần bạn thật sự có trong tay bộ dữ liệu đầy đủ, sạch sẽ và hoàn hảo?</p><p>📌 Nếu bạn đang ở vị trí phải:</p><ul><li>Đưa ra lựa chọn nhanh chóng trong khi dữ liệu chưa rõ ràng,</li><li>Dẫn dắt sản phẩm đi đúng hướng giữa vô vàn giả định,</li><li>Truyền cảm hứng cho đội ngũ tin tưởng vào quyết định chung,</li></ul><p>thì seminar lần này chính là không gian để bạn <strong>dừng lại, nhìn sâu hơn và trang bị những công cụ thực tiễn</strong>.</p><p>Tại đây, bạn sẽ cùng đồng nghiệp thảo luận những tình huống đời thực, lắng nghe chia sẻ từ lãnh đạo, và quan trọng nhất: <strong>học cách ra quyết định thông minh ngay cả khi dữ liệu không hoàn hảo</strong>.</p><p>Đừng bỏ lỡ cơ hội:<br>✨ Mở rộng góc nhìn ra quyết định,<br>✨ Cập nhật cách tiếp cận mới mẻ trong quản lý sản phẩm,<br>✨ Kết nối và học hỏi từ những đồng nghiệp nhiều trải nghiệm.</p><p>Đây không chỉ là một buổi chia sẻ, mà là cơ hội để bạn nhìn lại cách mình đang đưa ra quyết định và sẵn sàng bứt phá trong giai đoạn tiếp theo.</p><h2><strong>Thông tin chương trình</strong></h2><p><img src="https://product.momo.vn:1338/uploads/Poster_khoa_hoc_Anh_Thuan_7_2e9c0b66ab.jpg" alt="Poster khóa học - Anh Thuận (7).jpg"></p><h2><strong>Đăng ký tham dự</strong></h2><p>⏳ <strong>Hạn đăng ký: 13/09/2025</strong></p><p>Hãy nhanh tay đăng ký tham dự để giữ chỗ ngay hôm nay nhé</p><div class="raw-html-embed"><iframe src="https://docs.google.com/forms/d/e/1FAIpQLScPIVjntnE8FMoKPlKY7pSpZRH78ltf4wh4RmH2tRZq082tZQ/viewform?embedded=true" width="640" height="2424" frameborder="0" marginheight="0" marginwidth="0">Đang tải…</iframe></div><p>&nbsp;</p>',
    urlImage: null,
    totalViews: null,
    totalPost: null,
    totalLikes: null,
    publishDate: null,
    location: null,
    isFeatured: true,
    startDateTime: "2025-09-21T17:00:00.000Z",
    meta: {
      id: 7,
      MetaTitle:
        "Data & Decision-Making Leading Products in an Imperfect Landscape",
      MetaDescription: null,
      MetaKeywords: null,
      MetaAvatar: { data: null },
    },
    categoryName: ["Seminar"],
    coverImageUrl:
      "https://product.momo.vn:1338/uploads/Seminar_8_bf1bd8cf37.jpg",
    authors: [],
    id: 101,
  },
  {
    urlRewrite:
      "designing-for-value-product-strategy-business-model-and-monetization",
    createdAt: "2025-08-19T04:15:34.150Z",
    updatedAt: "2025-08-27T02:44:48.051Z",
    publishedAt: "2025-08-19T07:34:34.327Z",
    title:
      "Designing for Value: Product Strategy, Business Model & Monetization",
    description: "Từ trải nghiệm người dùng đến thành công kinh doanh",
    notionId: null,
    content:
      '<h2><strong>Giới thiệu</strong></h2><p>Trong hành trình phát triển sản phẩm, ưu tiên số một luôn là <strong>tạo ra giá trị cho người dùng</strong>. Một trải nghiệm tốt, một tính năng hữu ích hay một dịch vụ chạm đúng nhu cầu khách hàng, đó là nền tảng không thể thiếu.</p><p>Nhưng để sản phẩm thực sự <strong>tồn tại và phát triển dài hạn</strong>, chỉ “làm hài lòng khách hàng” thôi là chưa đủ. Doanh nghiệp còn cần xác định <strong>mô hình kinh doanh phù hợp</strong> và <strong>cách thức tạo doanh thu bền vững</strong>. Đây chính là điểm giao thoa, và đôi khi là mâu thuẫn giữa giá trị người dùng và giá trị kinh doanh.</p><p>👉 Seminar <strong>Designing for Value</strong> sẽ giúp bạn khám phá cách kết nối ba yếu tố: <strong>Product Strategy - Business Model - Monetization</strong>, để vừa mang lại trải nghiệm tốt cho khách hàng, vừa đảm bảo sản phẩm đóng góp vào tăng trưởng chung.</p><h2><strong>Thông tin chung</strong></h2><p><img src="https://product.momo.vn:1338/uploads/Poster_khoa_hoc_Anh_Thuan_6_013c606c0c.jpg" alt="Poster khóa học - Anh Thuận (6).jpg"></p><h2><strong>Đăng ký tham dự</strong></h2><p>⏳ <strong>Hạn đăng ký: 21/08/2025</strong><br>Đăng ký tham dự ngay để không bỏ lỡ cơ hội học hỏi và kết nối nhé.</p><div class="raw-html-embed"><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfNLUNzzEV7PjMbjrvh3Hk9zMmgjyE5l78N8IZAPOy708sK0g/viewform?embedded=true" width="640" height="2536" frameborder="0" marginheight="0" marginwidth="0">Đang tải…</iframe></div>',
    urlImage: null,
    totalViews: null,
    totalPost: null,
    totalLikes: null,
    publishDate: null,
    location: null,
    isFeatured: true,
    startDateTime: "2025-09-08T17:00:00.000Z",
    meta: null,
    categoryName: ["Seminar"],
    coverImageUrl:
      "https://product.momo.vn:1338/uploads/Seminar_9_0349a9e382.jpg",
    authors: [],
    id: 102,
  },
];
