import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/globals.css";

import { Toaster } from "sonner";

import { Footer } from "@/components/footer";
import Navigation from "@/components/main-nav/navigation";
import { AuthErrorHandler } from "@/features/auth/components/auth-error-handler";

// Cấu hình font Inter (cho tất cả text)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${inter.variable} ${inter.className} antialiased`}
      suppressHydrationWarning
    >
      <body className={`!overflow-x-hidden`}>
        <div className="relative z-10 bg-white">
          <Navigation />
          <main className=" ">{children}</main>
          <Footer />
          <Toaster />
          <AuthErrorHandler />
        </div>
      </body>
    </html>
  );
}
