import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";

import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark min-h-screen bg-background font-sans antialiased"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} amazing-rays relative z-[1] antialiased`}
        data-theme="dark"
      >
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
