import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Display } from "next/font/google";

import "@/styles/globals.css";

import { Toaster } from "sonner";

import { Footer } from "@/components/footer";
import Navigation from "@/components/main-nav/navigation";
import { AuthErrorHandler } from "@/features/auth/components/auth-error-handler";

// Cấu hình font Noto Sans Display (cho headings)
const notoSansDisplay = Noto_Sans_Display({
  subsets: ["latin"],
  variable: "--font-noto-sans-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

// Cấu hình font Noto Sans (cho body text)
const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${notoSansDisplay.variable} ${notoSans.variable} ${notoSans.className} antialiased`}
    >
      <body className={`!overflow-x-hidden`}>
        <div className="relative z-10 bg-white">
          <Navigation />
          <main className=" ">{children}</main>
          <Footer />
          <Toaster />
          <AuthErrorHandler />
        </div>
      </body>
    </html>
  );
}
